service: lululemon-stock-checker

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'sns:Publish'
          Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:lululemon-stock-checker-notification
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Scan'
          Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/lululemon-stock-checker-items

functions:
  checkItems:
    handler: handler.run
    events:
      - schedule: cron(0,15,30,45 * ? * * *)

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lululemon-stock-checker-items
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: lululemon-stock-checker-notification
        Subscription:
          - Protocol: email
            Endpoint: nicholasjyang@pm.me

plugins:
  - serverless-python-requirements
