service: lululemon-stock-checker

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'sns:Publish'
          Resource: arn:aws:sns:us-east-1:259356154792:lululemon-in-stock-notification
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Scan'
          Resource: arn:aws:dynamodb:us-east-1:259356154792:table/lulu_items

functions:
  cronHandler:
    handler: handler.run
    events:
      - schedule: cron(0,10,20,30,40,50 * ? * * *)

plugins:
  - serverless-python-requirements
